"use client";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Navbar from "@/lib/components/Navbar";
import Footer from "@/lib/components/Footer";

const queryClient = new QueryClient();

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <QueryClientProvider client={queryClient}>
                    <Navbar />
                    {children}
                    <Footer />
                </QueryClientProvider>
            </body>
        </html>
    );
}
